name: Run Contract Tests and Push Pact Files

on:
  push:
    branches:
      - main

jobs:
  pact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run contract tests
        run: dotnet test tests/Contract/InstallmentLoan.ContractTests.csproj

      - name: Checkout shared pact repo
        uses: actions/checkout@v4
        with:
          repository: suryamani-tw/pact-contracts
          token: ${{ secrets.PACT_PUSH_TOKEN }}
          path: pact-contracts

      - name: Copy pact files to main repo
        run: | 
          cp -r ./pacts/api/*  ./pact-contracts/pacts/api/ || echo "No pact api files to copy"
          cp -r ./pacts/messages/* ./pact-contracts/pacts/messages/ || echo "No pact messages files to copy"

      - name: Commit and push pact files
        run: |
          REPO_NAME=$(basename $(git rev-parse --show-toplevel))
          cd pact-contracts/pacts
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          if [ -d "api" ]; then
            git add api/* || echo "No pact api files to add"
          else
            echo "Api directory does not exist, skipping git add for api"
          fi
          if [ -d "messages" ]; then
            git add messages/* || echo "No pact messages files to add"
          else
            echo "Messages directory does not exist, skipping git add for messages"
          fi
          BUILD_NUMBER=${{ github.run_number }}
          GIT_SHA=${{ github.sha }}
          git commit -m "Update pact files from contract test run $REPO_NAME | build $BUILD_NUMBER | sha $GIT_SHA" || echo "No changes to commit"
          git push origin main
